# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'livereload' do
  watch(%r{.+\.(php|html)})
  watch(%r{assets/css/.+\.(css)})
  watch(%r{assets/js/.+\.(js)})
end

guard 'compass' do
  watch(/assets\/sass\/(.*)\.s[ac]ss/)
end

guard 'coffeescript', :input => 'assets/coffee', :output => 'assets/js', :hide_success => true
