# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'livereload' do
  watch(%r{.+\.(php|html)})
  watch(%r{css/.+\.(css)})
  watch(%r{js/.+\.(js)})
  watch(%r{sass/.+\.(scss|sass)})
  watch(%r{coffee/.+\.(coffee)})
end

guard 'compass' do
  watch(/^sass\/(.*)\.s[ac]ss/)
end

guard 'coffeescript', :input => 'coffee', :output => 'js', :hide_success => true
